### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by shenliyan01** [Luka0612/JEAR#5]
我运行之后，显示了FileNotFoundError: [Errno 2] No such file or directory: 'G:\\JEAR-master (1)going out on a limb_1\\data\\corpus_prepared.pickled' 这个问题，应该是数据集的问题吧，作者您方便共享吗，或者您可以说一下地址，我自己去下载吗
谢谢啦

**Comment by Luka0612** [comment]
@shenliyan01 http://cistern.cis.lmu.de/globalNormalization/globalNormalization_all.zip
